version: '3'

services:
  jenkins:
    image: saavi21/jenkins-on-docker-00:v1
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
